### ISSUE TITLE
Add Dashed lines

### ISSUE THREAD

**Issue by outoftrun** [SK-SpeedBit/js_chart#1]
I have made a small addition to your code, to add dashing to the lines
  "dash=[5,5]", I am testing it now, do you want to add this to your main truck
I am also testing on the ESP32 so far no problems

Nick

**Comment by SK-SpeedBit** [comment]
Hi
Thanks for your feedback.
I'd like to add your code.
But only after Christmas / New Year.
Now I have a lot of work (I have to earn some money :-)).
Additionally, the Chart was changed.
I corrected some bugs and added some new things.
I boast that this code has been inserted into the embedded device about
which half a year ago it was loud all over the world :-)
And on this occasion I just made a few corrections.
Please remind me about Your code in January at the latest, or after I
upload a new version (attach a notification if you don't have it).
Thank you for using my code and for developing the functionality.
I hope you are satisfied :-)
best regards
    Slawek

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Wolny
od wirusów. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

śr., 9 gru 2020 o 20:26 Nick Edgington <notifications@github.com>
napisał(a):

**Comment by SK-SpeedBit** [comment]
Done. Thanks!
